FROM devilbox/php-fpm:8.2-work-0.151

WORKDIR /var/www/html

COPY ./workspace /var/www/html/

# If you want to download more extension from PHP
# Please follow repo: https://github.com/kinhhodev/docker-for-php-extensions

# ---------- PHP Extensions --------- #


# ---------- End PHP Extensions --------- #

EXPOSE 9000