# version PHP 7.4

version: '3'
services:
  web_server:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      # mapping folder source in local to folder /var/www/html in container
      - ./workspace:/var/www/html
      # mapping folder config in local to folder /etc/nginx/nginx.conf in container
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - php-nginx-mysql-network
  
  # We need install some extension for php -> so we move image to Dockerfile
  php:
    image: php:7.4-fpm
    volumes:
      - ./workspace:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - php-nginx-mysql-network
  
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test_user1
      MYSQL_PASSWORD: test_user1_password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - php-nginx-mysql-network

networks:
  # name network
  php-nginx-mysql-network:
    driver: bridge
